version: '3.6'

networks:
  ebaysubscription-network:
    driver: bridge

services:
  ebaysubscription-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=ebaysubscription-mongo
      - REDIS_URL=ebaysubscription-redis
      - MAIL_HOST=ebaysubscription-mail
    depends_on:
      - ebaysubscription-mongo
      - ebaysubscription-redis
    networks:
      - ebaysubscription-network
    links:
      - ebaysubscription-mongo
      - ebaysubscription-redis
    container_name: ebaysubscription-api
    command: yarn dev
    ports:
      - 3333:3333

  ebaysubscription-queue:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=ebaysubscription-mongo
      - REDIS_URL=ebaysubscription-redis
      - MAIL_HOST=ebaysubscription-mail
    depends_on:
      - ebaysubscription-mongo
      - ebaysubscription-redis
    networks:
      - ebaysubscription-network
    links:
      - ebaysubscription-mongo
      - ebaysubscription-redis
    container_name: ebaysubscription-queue
    command: yarn queue

  ebaysubscription-mongo:
    image: mongo:latest
    container_name: ebaysubscription-mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - ebaysubscription-network

  ebaysubscription-redis:
    image: redis:latest
    container_name: ebaysubscription-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ebaysubscription-network

  ebaysubscription-mail:
    image: mailhog/mailhog
    container_name: ebaysubscription-mail
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - ebaysubscription-network
